connections = {
"objects": {
"aaron_ra5@hotmail.com": [
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": None,
"parent_name": "Aaron",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 902,
"user_name": "Aaron"
}
],
"appliancehomeservice@hotmail.com": [
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": None,
"parent_name": "JULIO CESAR MACEDA DIAZ",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 901,
"user_name": "JULIO CESAR MACEDA DIAZ"
}
],
"applianceservicemx@outlook.com": [
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": None,
"parent_name": "Daniel Crespo",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 1303,
"user_name": "Daniel Crespo"
}
],
"asistencia.tecnica@hotmail.com": [
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": None,
"parent_name": "Erick Llopis",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 813,
"user_name": "Erick Llopis"
}
],
"brendaro@prodigy.net.mx": [
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": 864,
"parent_name": "BRENDA CASTILLO",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 871,
"user_name": "HECTOR MORALES"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": 864,
"parent_name": "BRENDA CASTILLO",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 872,
"user_name": "ROBERTO GALLEGOS"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": False,
"parent_id": 864,
"parent_name": "BRENDA CASTILLO",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 873,
"user_name": "CARLOS ARIAS ENCINO"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": False,
"parent_id": None,
"parent_name": "BRENDA CASTILLO",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 864,
"user_name": "BRENDA CASTILLO"
}
],
"ceiservicio@hotmail.com": [
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": 840,
"parent_name": "JOSAFAT COLLAZO HERRERA",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 849,
"user_name": "Luis Gerardo carbajal moncada"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": None,
"parent_name": "JOSAFAT COLLAZO HERRERA",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 840,
"user_name": "JOSAFAT COLLAZO HERRERA"
}
],
"ernesto.galancuellar@gmail.com": [
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": None,
"parent_name": "Ernesto Galan",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 898,
"user_name": "Ernesto Galan"
}
],
"fidelrms@hotmail.com": [
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": None,
"parent_name": "fidel rafael mendoza de los santos",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 911,
"user_name": "fidel rafael mendoza de los santos"
}
],
"g-chanes@hotmail.com": [
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": 865,
"parent_name": "Gerardo Chanes Sanchez",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 877,
"user_name": "andres enrique gurrola magallon"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": 865,
"parent_name": "Gerardo Chanes Sanchez",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 876,
"user_name": "cesar adrian chanes martinez"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": None,
"parent_name": "Gerardo Chanes Sanchez",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 865,
"user_name": "Gerardo Chanes Sanchez"
}
],
"gerardo@install-it.com.mx": [
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": 853,
"parent_name": "Gerardo Ortiz",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 855,
"user_name": "Alejandro Ferrer Sanchez"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": 853,
"parent_name": "Gerardo Ortiz",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 856,
"user_name": "Jose Luis Trejo Castillo"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": False,
"parent_id": None,
"parent_name": "Gerardo Ortiz",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 853,
"user_name": "Gerardo Ortiz"
}
],
"gerardocarbajal_14@hotmail.com2": [
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": None,
"parent_name": "luis gerardo carbajal moncada",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 841,
"user_name": "luis gerardo carbajal moncada"
}
],
"instalacionesrova@yahoo.com.mx": [
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": None,
"parent_name": "Roberto Vargas Vega",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 894,
"user_name": "Roberto Vargas Vega"
}
],
"josepato@infosync.mx": [
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": False,
"parent_id": 126,
"parent_name": "Jose Patricio Villarreal",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 712,
"user_name": "Usuario"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": False,
"parent_id": 126,
"parent_name": "Jose Patricio Villarreal",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 129,
"user_name": "Tomas Castro"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": 126,
"parent_name": "Jose Patricio Villarreal",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 557,
"user_name": "Gerardo Saul Gausin Valle"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": False,
"parent_id": 126,
"parent_name": "Jose Patricio Villarreal",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 437,
"user_name": "Rolando Cruz Verastegui"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": False,
"parent_id": 126,
"parent_name": "Jose Patricio Villarreal",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 806,
"user_name": "Raquel Sampayo"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": False,
"parent_id": 126,
"parent_name": "Jose Patricio Villarreal",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 724,
"user_name": "FEMSA"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": 126,
"parent_name": "Jose Patricio Villarreal",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 152,
"user_name": "Emmanuel Garcia"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": 126,
"parent_name": "Jose Patricio Villarreal",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 767,
"user_name": "Leonelo Pruebas Villarreal"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": 126,
"parent_name": "Jose Patricio Villarreal",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 962,
"user_name": "Control de Plagas Ancpuac 2016"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": False,
"parent_id": 126,
"parent_name": "Jose Patricio Villarreal",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 127,
"user_name": "Antonio Garza"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": 126,
"parent_name": "Jose Patricio Villarreal",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 949,
"user_name": "Leslie Ruelas"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": False,
"parent_id": 126,
"parent_name": "Jose Patricio Villarreal",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 975,
"user_name": "Jonathan Alvarado"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": False,
"parent_id": 126,
"parent_name": "Jose Patricio Villarreal",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 985,
"user_name": "Direccion"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": False,
"parent_id": 126,
"parent_name": "Jose Patricio Villarreal",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 133,
"user_name": "Hector Omar Vazquez D."
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": 126,
"parent_name": "Jose Patricio Villarreal",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 131,
"user_name": "Cecilia Urbina"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": False,
"parent_id": 126,
"parent_name": "Jose Patricio Villarreal",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 634,
"user_name": "Solucion Pest Control"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": False,
"parent_id": 126,
"parent_name": "Jose Patricio Villarreal",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 973,
"user_name": "Selene Ocana"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": None,
"parent_name": "Jose Patricio Villarreal",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 126,
"user_name": "Jose Patricio Villarreal"
}
],
"juancarlos_rleal@yahoo.com.mx": [
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": False,
"parent_id": 790,
"parent_name": "Juan Carlos Rodriguez",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 819,
"user_name": "Benjamin Abraham Sanchez Lopez"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": None,
"parent_name": "Juan Carlos Rodriguez",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 790,
"user_name": "Juan Carlos Rodriguez"
}
],
"juanr@ruizt.com": [
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": False,
"parent_id": None,
"parent_name": "juan ramon alvarez ramirez",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 1084,
"user_name": "juan ramon alvarez ramirez"
}
],
"leonelo.villarreal@hotmail.com": [
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": 789,
"parent_name": "Leonelo Villarreal",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 817,
"user_name": "Antelmo"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": 789,
"parent_name": "Leonelo Villarreal",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 818,
"user_name": "Gelacio nunez"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": 789,
"parent_name": "Leonelo Villarreal",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 906,
"user_name": "servicio wolf"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": None,
"parent_name": "Leonelo Villarreal",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 789,
"user_name": "Leonelo Villarreal"
}
],
"re_acon@yahoo.com.mx": [
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": False,
"parent_id": None,
"parent_name": "carlos chavez ochoa",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 899,
"user_name": "carlos chavez ochoa"
}
],
"rodrigo_servitec@outlook.com": [
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": 839,
"parent_name": "Rodrigo Moises Rosas Cuevas",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 879,
"user_name": "LEOBARDO LUGO JUAREZ"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": False,
"parent_id": 839,
"parent_name": "Rodrigo Moises Rosas Cuevas",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 1002,
"user_name": "RAFAEL CRUZ"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": 839,
"parent_name": "Rodrigo Moises Rosas Cuevas",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 851,
"user_name": "Emiliano Gonzalez Ventura"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": 839,
"parent_name": "Rodrigo Moises Rosas Cuevas",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 882,
"user_name": "JAVIER RESENDIZ MORALES"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": 839,
"parent_name": "Rodrigo Moises Rosas Cuevas",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 850,
"user_name": "Alejandro Alvarado Ramirez"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": 839,
"parent_name": "Rodrigo Moises Rosas Cuevas",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 881,
"user_name": "ADRIAN RAMIREZ SANCHEZ"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": 839,
"parent_name": "Rodrigo Moises Rosas Cuevas",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 852,
"user_name": "Omar Estrada Fuentes"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": 839,
"parent_name": "Rodrigo Moises Rosas Cuevas",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 844,
"user_name": "Jose Luis Trillo Ramirez"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": 839,
"parent_name": "Rodrigo Moises Rosas Cuevas",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 880,
"user_name": "ANUAR LOPEZ ANGELES"
},
{
"activity": "Solicitud de Refacciones",
"daily_count": 1,
"end_date": 1480955401,
"id": 344242,
"item": 6248,
"parent": 839,
"seconds_duration": "2 mins 53 segs",
"start_date": 1480955228,
"user": 839,
"user_name": "Rodrigo Moises Rosas Cuevas"
}
],
"saldivardiazjavier@hotmail.com": [
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": None,
"parent_name": "Javier Saldivar",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 812,
"user_name": "Javier Saldivar"
}
],
"servicio@serviciotecnico.com.mx": [
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": None,
"parent_name": "ROBERTO ROSAS FRANCO",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 854,
"user_name": "ROBERTO ROSAS FRANCO"
}
],
"servicioclientesmty@gmail.com": [
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": False,
"parent_id": 820,
"parent_name": "Samuel Pang",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 833,
"user_name": "Rogelio Arriaga Medina"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": False,
"parent_id": 820,
"parent_name": "Samuel Pang",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 834,
"user_name": "Gerardo Lopez Ramirez"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": None,
"parent_name": "Samuel Pang",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 820,
"user_name": "Samuel Pang"
}
],
"servicios@soscocinas.com.mx": [
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": None,
"parent_name": "EDGAR CAMACHO PARTIDA",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 900,
"user_name": "EDGAR CAMACHO PARTIDA"
}
],
"servitec_leon_@hotmail.com": [
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": 892,
"parent_name": "ANTONIO ALFARO ROSAS",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 895,
"user_name": "MARCO ANTONIO FLORES"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": None,
"parent_name": "ANTONIO ALFARO ROSAS",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 892,
"user_name": "ANTONIO ALFARO ROSAS"
}
],
"servitecrf.aca@gmail.com": [
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": 897,
"parent_name": "Rodolfo Rosas Franco",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 903,
"user_name": "Antonio Abad Garcia Herrera"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": 897,
"parent_name": "Rodolfo Rosas Franco",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 904,
"user_name": "Edgar Hernndez Lopez"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": None,
"parent_name": "Rodolfo Rosas Franco",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 897,
"user_name": "Rodolfo Rosas Franco"
}
],
"tecyserv@prodigy.net.mx": [
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": 837,
"parent_name": "jesus tinoco",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 847,
"user_name": "Magaly Mejia"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": False,
"parent_id": 837,
"parent_name": "jesus tinoco",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 846,
"user_name": "Jose Ortega"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": 837,
"parent_name": "jesus tinoco",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 848,
"user_name": "Jose Tinoco"
},
{
"activity": "Orden de Instalacion",
"daily_count": 1,
"end_date": 1480954568,
"id": 344236,
"item": 6180,
"parent": 837,
"seconds_duration": "10 mins 36 segs",
"start_date": 1480953931,
"user": 837,
"user_name": "jesus tinoco"
}
],
"urva.iesa@hotmail.com": [
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": False,
"parent_id": 893,
"parent_name": "JOEL URQUIDEZ",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 896,
"user_name": "ROBERTO PERAZA"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": False,
"parent_id": None,
"parent_name": "JOEL URQUIDEZ",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 893,
"user_name": "JOEL URQUIDEZ"
}
],
"ventas@procool.com.mx": [
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": False,
"parent_id": 913,
"parent_name": "Jorge perez",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 1093,
"user_name": "ISAAC RAFAEL PEREZ CAMPOS"
},
{
"activity": "Orden de Servicio",
"daily_count": 1,
"end_date": 1480963432,
"id": 344315,
"item": 6143,
"parent": 913,
"seconds_duration": "58 segs",
"start_date": 1480963373,
"user": 913,
"user_name": "Jorge perez"
}
],
"zavalamendozae@hotmail.com": [
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": False,
"parent_id": 874,
"parent_name": "enrique zavala mendoza",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 875,
"user_name": "ANTONIO SANCHEZ CARRILLO"
},
{
"activity": "Ninguna actividad el dia de hoy",
"daily_count": 0,
"end_date": None,
"id": 0,
"last_login": 0,
"online": True,
"parent_id": None,
"parent_name": "enrique zavala mendoza",
"resource_uri": None,
"seconds_duration": "N/A",
"start_date": None,
"user_id": 874,
"user_name": "enrique zavala mendoza"
}
]
}
}
